---
all:
  hosts:
    192.168.100.10:
    192.168.100.11:
    192.168.100.12:
    192.168.100.13:
    192.168.100.14:
  vars:
    ansible_network_os: "ios"
    ansible_user: "cisco"
    ansible_password: "cisco!123"
    ansible_python_interpreter: "/usr/bin/env python"
    ntp_server1: "192.0.2.1"
    ntp_server2: "192.0.2.3"
    